openapi: 3.0.3
info:
  contact:
    email: support@capenetworks.com
    name: We need a person
    url: http://we.dont.care.yet.com/contact
  description: Nice description goes here
  license:
    name: "No idea, but we need something"
  termsOfService: http://we.dont.care.yet.com/term-of-service
  title: Configuration Api
  version: 1.9.0
servers:
- url: https://api.capenetworks.com
- url: https://api.staging.capedev.io
tags:
- name: api
- name: v1
- name: configuration
- name: groups
- name: health
- name: sensor-group-assignments
- name: wired-networks
- name: wireless-networks
paths:
  /configuration/app/v1/groups:
    get:
      description: Lists groups matching provided criteria
      operationId: groups_get_configuration_app_v1_groups_get
      parameters:
      - explode: true
        in: query
        name: uid
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 50
          title: Limit
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsGetResponse'
          description: Successful Response
        "4XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Client Error
        "5XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
      security:
      - HTTPBearer: []
      summary: Groups Get
      tags:
      - configuration
      x-stability-level: alpha
    post:
      description: Create a new group with the group identified in `parent_uid` as
        its parent
      operationId: groups_post_configuration_app_v1_groups_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsPostRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsPostResponse'
          description: Successful Response
        "4XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Client Error
        "5XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
      security:
      - HTTPBearer: []
      summary: Groups Post
      tags:
      - configuration
  /configuration/app/v1/sensor-group-assignments:
    get:
      description: Get a list of sensor group assignments
      operationId: get_configuration_app_v1_sensor_group_assignments_get
      parameters:
      - explode: true
        in: query
        name: uid
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 50
          title: Limit
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorGroupAssignmentsResponse'
          description: Successful Response
        "4XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Client Error
        "5XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
      security:
      - HTTPBearer: []
      summary: Get
      tags:
      - configuration
      x-stability-level: alpha
  /configuration/app/v1/wired-networks:
    get:
      description: Get a list of wired networks
      operationId: get_configuration_app_v1_wired_networks_get
      parameters:
      - explode: true
        in: query
        name: uid
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 50
          title: Limit
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WiredNetworksResponse'
          description: Successful Response
        "4XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Client Error
        "5XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
      security:
      - HTTPBearer: []
      summary: Get
      tags:
      - configuration
      x-stability-level: alpha
  /configuration/app/v1/wireless-networks:
    get:
      description: Get a list of wireless networks
      operationId: get_configuration_app_v1_wireless_networks_get
      parameters:
      - explode: true
        in: query
        name: uid
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: cursor
        required: false
        schema:
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 50
          title: Limit
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WirelessNetworksResponse'
          description: Successful Response
        "4XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Client Error
        "5XX":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Server Error
      security:
      - HTTPBearer: []
      summary: Get
      tags:
      - configuration
      x-stability-level: alpha
components:
  schemas:
    ErrorDetail:
      example:
        message: message
      properties:
        message:
          title: Message
          type: string
      required:
      - message
      title: ErrorDetail
      type: object
    ErrorResponse:
      example:
        detail:
        - message: message
        - message: message
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ErrorDetail'
          title: Detail
          type: array
      required:
      - detail
      title: ErrorResponse
      type: object
    GroupsGetItem:
      example:
        uid: uid
        path: path
        parent_uid: parent_uid
        name: name
      properties:
        uid:
          title: Uid
          type: string
        name:
          title: Name
          type: string
        path:
          title: Path
          type: string
        parent_uid:
          nullable: true
          type: string
      required:
      - name
      - parent_uid
      - path
      - uid
      title: GroupsGetItem
      type: object
    GroupsGetResponse:
      example:
        pagination:
          next: next
          previous: previous
          last: last
          limit: 0
          first: first
        groups:
        - uid: uid
          path: path
          parent_uid: parent_uid
          name: name
        - uid: uid
          path: path
          parent_uid: parent_uid
          name: name
      properties:
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
        groups:
          items:
            $ref: '#/components/schemas/GroupsGetItem'
          title: Groups
          type: array
      required:
      - groups
      - pagination
      title: GroupsGetResponse
      type: object
    GroupsPostRequest:
      example:
        parent_uid: parent_uid
        name: name
      properties:
        parent_uid:
          title: Parent Uid
          type: string
        name:
          title: Name
          type: string
      required:
      - name
      - parent_uid
      title: GroupsPostRequest
      type: object
    GroupsPostResponse:
      example:
        uid: uid
        path: path
        parent_uid: parent_uid
        name: name
      properties:
        parent_uid:
          title: Parent Uid
          type: string
        name:
          title: Name
          type: string
        uid:
          title: Uid
          type: string
        path:
          title: Path
          type: string
      required:
      - name
      - parent_uid
      - path
      - uid
      title: GroupsPostResponse
      type: object
    PaginationDetails:
      example:
        next: next
        previous: previous
        last: last
        limit: 0
        first: first
      properties:
        limit:
          title: Limit
          type: integer
        next:
          nullable: true
          type: string
        previous:
          nullable: true
          type: string
        first:
          nullable: true
          type: string
        last:
          nullable: true
          type: string
      required:
      - first
      - last
      - limit
      - next
      - previous
      title: PaginationDetails
      type: object
    SensorGroupAssignment:
      example:
        group_uid: group_uid
        uid: uid
        sensor_uid: sensor_uid
      properties:
        uid:
          title: Uid
          type: string
        group_uid:
          title: Group Uid
          type: string
        sensor_uid:
          title: Sensor Uid
          type: string
      required:
      - group_uid
      - sensor_uid
      - uid
      title: SensorGroupAssignment
      type: object
    SensorGroupAssignmentsResponse:
      example:
        sensor_group_assignments:
        - group_uid: group_uid
          uid: uid
          sensor_uid: sensor_uid
        - group_uid: group_uid
          uid: uid
          sensor_uid: sensor_uid
        pagination:
          next: next
          previous: previous
          last: last
          limit: 0
          first: first
      properties:
        sensor_group_assignments:
          items:
            $ref: '#/components/schemas/SensorGroupAssignment'
          title: Sensor Group Assignments
          type: array
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
      - pagination
      - sensor_group_assignments
      title: SensorGroupAssignmentsResponse
      type: object
    WiredNetwork:
      example:
        vlan_id: 6
        created_at: 2000-01-23T04:56:07.000+00:00
        sensor_count: 0
        external_connectivity: true
        dns_lookup_domain: dns_lookup_domain
        disable_edns: true
        uid: uid
        security: security
        ip_version: ip_version
        updated_at: 2000-01-23T04:56:07.000+00:00
        alias: alias
        disabled: true
        use_dns64: true
      properties:
        uid:
          title: Uid
          type: string
        alias:
          title: Alias
          type: string
        ip_version:
          title: Ip Version
          type: string
        sensor_count:
          title: Sensor Count
          type: integer
        updated_at:
          format: date-time
          title: Updated At
          type: string
        created_at:
          format: date-time
          title: Created At
          type: string
        disabled:
          title: Disabled
          type: boolean
        security:
          nullable: true
          type: string
        dns_lookup_domain:
          nullable: true
          type: string
        disable_edns:
          title: Disable Edns
          type: boolean
        use_dns64:
          title: Use Dns64
          type: boolean
        external_connectivity:
          title: External Connectivity
          type: boolean
        vlan_id:
          nullable: true
          type: integer
      required:
      - alias
      - created_at
      - disable_edns
      - disabled
      - dns_lookup_domain
      - external_connectivity
      - ip_version
      - security
      - sensor_count
      - uid
      - updated_at
      - use_dns64
      - vlan_id
      title: WiredNetwork
      type: object
    WiredNetworksResponse:
      example:
        pagination:
          next: next
          previous: previous
          last: last
          limit: 0
          first: first
        wired_networks:
        - vlan_id: 6
          created_at: 2000-01-23T04:56:07.000+00:00
          sensor_count: 0
          external_connectivity: true
          dns_lookup_domain: dns_lookup_domain
          disable_edns: true
          uid: uid
          security: security
          ip_version: ip_version
          updated_at: 2000-01-23T04:56:07.000+00:00
          alias: alias
          disabled: true
          use_dns64: true
        - vlan_id: 6
          created_at: 2000-01-23T04:56:07.000+00:00
          sensor_count: 0
          external_connectivity: true
          dns_lookup_domain: dns_lookup_domain
          disable_edns: true
          uid: uid
          security: security
          ip_version: ip_version
          updated_at: 2000-01-23T04:56:07.000+00:00
          alias: alias
          disabled: true
          use_dns64: true
      properties:
        wired_networks:
          items:
            $ref: '#/components/schemas/WiredNetwork'
          title: Wired Networks
          type: array
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
      - pagination
      - wired_networks
      title: WiredNetworksResponse
      type: object
    WirelessNetwork:
      example:
        hidden: true
        created_at: 2000-01-23T04:56:07.000+00:00
        sensor_count: 0
        external_connectivity: true
        ssid: ssid
        dns_lookup_domain: dns_lookup_domain
        disable_edns: true
        uid: uid
        security: security
        ip_version: ip_version
        updated_at: 2000-01-23T04:56:07.000+00:00
        alias: alias
        disabled: true
        use_dns64: true
        band_locking: band_locking
      properties:
        uid:
          title: Uid
          type: string
        alias:
          title: Alias
          type: string
        ssid:
          title: Ssid
          type: string
        security:
          nullable: true
          type: string
        ip_version:
          title: Ip Version
          type: string
        sensor_count:
          title: Sensor Count
          type: integer
        updated_at:
          format: date-time
          title: Updated At
          type: string
        created_at:
          format: date-time
          title: Created At
          type: string
        disabled:
          title: Disabled
          type: boolean
        hidden:
          title: Hidden
          type: boolean
        band_locking:
          title: Band Locking
          type: string
        dns_lookup_domain:
          nullable: true
          type: string
        disable_edns:
          title: Disable Edns
          type: boolean
        use_dns64:
          title: Use Dns64
          type: boolean
        external_connectivity:
          title: External Connectivity
          type: boolean
      required:
      - alias
      - band_locking
      - created_at
      - disable_edns
      - disabled
      - dns_lookup_domain
      - external_connectivity
      - hidden
      - ip_version
      - security
      - sensor_count
      - ssid
      - uid
      - updated_at
      - use_dns64
      title: WirelessNetwork
      type: object
    WirelessNetworksResponse:
      example:
        wireless_networks:
        - hidden: true
          created_at: 2000-01-23T04:56:07.000+00:00
          sensor_count: 0
          external_connectivity: true
          ssid: ssid
          dns_lookup_domain: dns_lookup_domain
          disable_edns: true
          uid: uid
          security: security
          ip_version: ip_version
          updated_at: 2000-01-23T04:56:07.000+00:00
          alias: alias
          disabled: true
          use_dns64: true
          band_locking: band_locking
        - hidden: true
          created_at: 2000-01-23T04:56:07.000+00:00
          sensor_count: 0
          external_connectivity: true
          ssid: ssid
          dns_lookup_domain: dns_lookup_domain
          disable_edns: true
          uid: uid
          security: security
          ip_version: ip_version
          updated_at: 2000-01-23T04:56:07.000+00:00
          alias: alias
          disabled: true
          use_dns64: true
          band_locking: band_locking
        pagination:
          next: next
          previous: previous
          last: last
          limit: 0
          first: first
      properties:
        wireless_networks:
          items:
            $ref: '#/components/schemas/WirelessNetwork'
          title: Wireless Networks
          type: array
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
      - pagination
      - wireless_networks
      title: WirelessNetworksResponse
      type: object
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http
